### ISSUE TITLE
Hello i have problem with resolution.

### ISSUE THREAD

**Issue by slee30** [cdaein/mica-gd300#2]
Hello i have problem with resolution. All my illustration files in After Effects look very pixelated. I checked all the vector layer check boxes, but they are still pixelated. Anyone has same problem???

<img width="1680" alt="Screen Shot 2019-09-20 at 11 18 01 PM" src="https://user-images.githubusercontent.com/47001715/65367311-22e2ab80-dbfd-11e9-82aa-6c4565a76f97.png">

**Comment by Arran321** [comment]
I think Dae In mentioned in the class before, you can try to select all the layers, and click the second button on the right(the one like a sun), see if it gets better

**Comment by slee30** [comment]
I did click the second one from the left and it did change little bit better, but its just little bit.

**Comment by crystalhuang0107** [comment]
Hello!
   I have the same problem too. After I clicked the second icon (For Vector layers, continuously rasterize), the resolution change a bit, but still not 100% clear or in a high-resolution. So I just make the artboard of that original document a little bit bigger (700px). It worked when I imported back to AE. But I also realized it seems blurry before may because you make the view more than 100% in AE. When the view is back to 100%, it does appear clear.

**Comment by cdaein** [comment]
You can rescale a vector (AI) layer as much as you want, but that is on the *layer level*. If you zoom in the whole composition, everything will look pixelated and that's expected because at the end, the video itself is pixel-based. So, keep the composition at 500x500 and preview at 100% zoom level.
