### ISSUE TITLE
Grains in exported GIF

### ISSUE THREAD

**Issue by ahannahn** [cdaein/mica-gd300#3]
Hi,

I am having an issue with my exported gif file. Everything seems to be fine, but the colors have weird grains and textures. It's very obvious and noticeable in the sun of my illustration. I can't seem to figure out a way to get rid of the little dots. Does this have something to do with the resolution? I'd greatly appreciate any sort of advice/help! Thanks in advance!!

<img width="499" alt="Screen Shot 2019-09-23 at 12 04 27 PM" src="https://user-images.githubusercontent.com/46966582/65446822-33fd0980-de03-11e9-9b54-9fc79a30de46.png">

**Comment by cdaein** [comment]
that's because gif **only supports 256 colors**. I suggest tweaking the settings in GIF export dialog. - starting with number of colors, and different algorithms (adaptive, selective, diffusions, etc.) Changing them while testing the result on the left preview image panel will give you some rough ideas. Do let us know if this helps.
